# Generated by Django 4.2.6 on 2024-02-27 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_recepcao', '0004_tblvisitante_assinatura_digital'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblvisitante',
            name='login',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_recepcao.login'),
        ),
    ]
