# Generated by Django 4.2.6 on 2024-02-27 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_recepcao', '0006_tblvisitante_lixeira_registroentrada_lixeira'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblvisitante_lixeira',
            name='login',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_recepcao.login'),
        ),
    ]
