# Generated by Django 4.2.6 on 2024-02-27 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_recepcao', '0007_alter_tblvisitante_lixeira_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblvisitante_lixeira',
            name='assinatura_digital',
        ),
    ]
