# Generated by Django 4.2.6 on 2024-02-21 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_recepcao', '0003_rename_id_visitante_endereco_visitante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblvisitante',
            name='assinatura_digital',
            field=models.ImageField(blank=True, null=True, upload_to='assinaturas/'),
        ),
    ]
