# Generated by Django 4.2.6 on 2024-02-20 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_recepcao', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registroentrada',
            old_name='id_entrada2',
            new_name='id_visitante',
        ),
    ]
