# Generated by Django 4.2.6 on 2024-02-20 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_recepcao', '0002_rename_id_entrada2_registroentrada_id_visitante'),
    ]

    operations = [
        migrations.RenameField(
            model_name='endereco',
            old_name='id_visitante',
            new_name='visitante',
        ),
        migrations.RenameField(
            model_name='registroentrada',
            old_name='id_visitante',
            new_name='visitante',
        ),
    ]
